---
title: "R Notebook"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = TRUE, cache = FALSE)
library(here)
# here::here()
knitr::opts_knit$set(root.dir = here::here())
```

```{r load_libs_sources, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}
source('./R/utils_av.R')
```

```{r new_functions}

seas_yr_growth <- function(data_ts, freq = 4) {
  this_rgdp_tsb <- tsibble::as_tsibble(this_rgdp_ts)

  seas_gr  <- this_rgdp_tsb %>% rename(log_rgdp = value) %>% 
    mutate(difflog_gr =  100 * difference(log_rgdp, lag = 4),
           gr = 100 * difference(exp(log_rgdp), lag = 4) / 
                 dplyr::lag(exp(log_rgdp), n = 4),
         )

  year_gr <- seas_gr %>% index_by(year_index = year(index)) %>% 
  summarise(y_logdiff = mean(difflog_gr, na.rm = TRUE),
            y_ave_gr = mean(gr, na.rm = TRUE),
            y_rgdp = sum(exp(log_rgdp))
            ) %>% 
  mutate(y_tot_gr = 100*difference(y_rgdp)/lag(y_rgdp)) 
  
  return(list(seasonal_growth = seas_gr, year_growth = year_gr))

}

print_growths <- function(seas_and_yr_gr) {
  seas_gr <- seas_and_yr_gr[["seasonal_growth"]]
  year_gr <- seas_and_yr_gr[["year_growth"]]

  a <- knitr::kable(tail(as_tibble(seas_gr) %>% select(-log_rgdp), n = 8), 
             digits = 1, align = 'lcc')

  b <- knitr::kable(tail(as_tibble(year_gr) %>% select(-y_rgdp), n = 5),
               digits = 1, align = 'lccc')  
  
  walk(list(a,b), print)
  
}

```



## Initial data


```{r preferences_and_load_data, warning=FALSE}
arima_res_suffix <- "_min"
arima_rds_path = "data/sarimax_objects_"
country_name <- "Bolivia_activ"
# data_path <- "./data/excel/Chile.xlsx"
data_path <- paste0("./data/excel/", country_name, ".xlsx")
external_data_path <- "./data/external/external_us.xlsx"
final_forecast_horizon <- c(2019, 12)
h_max <-  8 # last rgdp data is 2017 Q4
test_length <- h_max
number_of_cv = 8
train_span = 16
use_demetra <- TRUE

use_dm_force_constant <- TRUE
is_log_log <- TRUE
lambda_0_in_auto <- FALSE
mean_logical_in_auto <- TRUE
max_x_lag <- 2

all_arima_data <- ts_data_for_arima(data_path = data_path, 
                                    external_data_path = external_data_path,
                                    all_logs = is_log_log)

this_rgdp_ts <- all_arima_data[["rgdp_ts"]]
this_rgdp_ts <- na.omit(this_rgdp_ts)

this_internal_monthly_ts <- all_arima_data[["monthly_ts"]]
this_external_monthly_ts <- all_arima_data[["external_monthly_ts"]]

internal_monthly_names <- colnames(this_internal_monthly_ts)
external_monthly_names <- colnames(this_external_monthly_ts)

```

Log transformation applied to all variables. Data obtained from the excel file `r print(data_path)` 

### Quarterly real GDP


```{r plot_level_rgdp}
autoplot(this_rgdp_ts) + 
  ggtitle(paste("Quarterly GDP")) 

```


```{r plot_yoy_gr_rgdp}

autoplot(make_yoy_ts(this_rgdp_ts, is_log = TRUE)) + 
  ggtitle(paste("YoY growth, Quarterly GDP")) 
```


```{r plot_level_e_i}
autoplot(this_internal_monthly_ts, series = "internal") + 
  autolayer(this_external_monthly_ts, series = "external")

```

```{r plot_yoy_growth_e_i}
autoplot(make_yoy_ts(this_internal_monthly_ts, freq = 12, is_log = TRUE),
         series = "internal") + 
  autolayer(make_yoy_ts(this_external_monthly_ts, freq = 12, is_log = TRUE),
            series = "external") 
  

```



```{r gr_rgdp_data}

gr_q_y <- seas_yr_growth(this_rgdp_ts)

print_growths(gr_q_y)

```



## Initial GDP specification and forecast

## Forecasting and extending monthly data

### Implied 

